[package]
name = "simple-ping-server"
version = "0.1.0"
authors = ["DEDZTBH <peiqial@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shellwords = "1.1.0"
anyhow = "1.0.38"